In [ ]:
! pip install sqlalchemy duckdb

In [92]:
import pandas as pd
import duckdb

In [93]:
df = pd.read_csv("data/processed/churn_clean.csv")

df.head()

,customer_id,count,country,state,city,zip_code,lat_long,latitude,longitude,gender,...,internet_category,service_count,engagement_score,customer_status,location,avg_revenue_per_month,coordinates,churn_reason_category,loyalty_level,customer_segment
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,DSL,3,48.19,Inactive,"Los Angeles, California",54.075000,"(33.964131, -118.272783)",Churned,New,At Risk
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Fiber,1,32.81,Inactive,"Los Angeles, California",75.825000,"(34.059281, -118.30742)",Churned,New,Standard
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Fiber,5,81.92,Inactive,"Los Angeles, California",102.562500,"(34.048013, -118.293953)",Churned,New,VIP At Risk
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Fiber,6,91.23,Inactive,"Los Angeles, California",108.787500,"(34.062125, -118.315709)",Churned,Regular,VIP At Risk
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Fiber,6,103.00,Inactive,"Los Angeles, California",102.781633,"(34.039224, -118.266293)",Churned,Loyal,VIP At Risk

In [94]:
con = duckdb.connect()

In [95]:
con.register("customer_churn", df)

In [96]:
query = """
SELECT *
FROM customer_churn
LIMIT 5;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [ ]:
query = """
SELECT COUNT(*) AS total_customers
FROM customer_churn;
"""

dashboard_state = dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

dashboard_state.to_csv(
"data/processed/dashboard_state.csv",
index=False
)

In [ ]:
query = """
SELECT COUNT(*) AS churned_customers
FROM customer_churn
WHERE churn_label='Yes';
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   churned_customers
0               1869

In [ ]:
query = """
SELECT
ROUND(
100.0 *
SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
/COUNT(*),2) AS churn_rate
FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   churn_rate
0       26.54

In [ ]:
query = """
SELECT
ROUND(AVG(monthly_charges),2)
AS average_monthly_charges
FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   average_monthly_charges
0                    64.76

In [ ]:
query = """
SELECT
ROUND(AVG(cltv),2)
AS average_cltv
FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   average_cltv
0        4400.3

In [ ]:
query = """
SELECT
ROUND(AVG(tenure_months),2)
AS average_tenure
FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   average_tenure
0           32.37

In [ ]:
query = """
SELECT
gender,
COUNT(*) AS customers
FROM customer_churn
GROUP BY gender
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   gender  customers
0    Male       3555
1  Female       3488

In [ ]:
query = """
SELECT
contract,
COUNT(*) AS customers
FROM customer_churn
GROUP BY contract
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  customers
0  Month-to-month       3875
1        Two year       1695
2        One year       1473

In [ ]:
query = """
SELECT
internet_service,
COUNT(*) AS customers
FROM customer_churn
GROUP BY internet_service
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  internet_service  customers
0      Fiber optic       3096
1              DSL       2421
2               No       1526

In [ ]:
query = """
SELECT
payment_method,
COUNT(*) AS customers
FROM customer_churn
GROUP BY payment_method
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

              payment_method  customers
0           Electronic check       2365
1               Mailed check       1612
2  Bank transfer (automatic)       1544
3    Credit card (automatic)       1522

In [ ]:
query = """
SELECT
customer_segment,
COUNT(*) AS customers
FROM customer_churn
GROUP BY customer_segment
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  customers
0              VIP       2492
1         Standard       2280
2          At Risk       1241
3      VIP At Risk       1030

In [ ]:
query = """
SELECT
loyalty_level,
COUNT(*) AS customers
FROM customer_churn
GROUP BY loyalty_level
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level  customers
0           New       2175
1       Regular       1856
2         Loyal       1594
3  Highly Loyal       1407
4           NaN         11

In [ ]:
query = """
SELECT
contract,
COUNT(*) AS churned_customers
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY contract
ORDER BY churned_customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  churned_customers
0  Month-to-month               1655
1        One year                166
2        Two year                 48

In [ ]:
query = """
SELECT
internet_service,
COUNT(*) AS churned_customers
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY internet_service
ORDER BY churned_customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  internet_service  churned_customers
0      Fiber optic               1297
1              DSL                459
2               No                113

In [ ]:
query = """
SELECT
state,
COUNT(*) AS customers
FROM customer_churn
GROUP BY state
ORDER BY customers DESC
LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state  customers
0  California       7043

In [ ]:
query = """
SELECT
    contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
/COUNT(*),2) AS churn_rate
FROM customer_churn
GROUP BY contract
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  total_customers  churned_customers  churn_rate
0  Month-to-month             3875             1655.0       42.71
1        One year             1473              166.0       11.27
2        Two year             1695               48.0        2.83

In [ ]:
query = """
SELECT
    payment_method,
    COUNT(*) AS customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
/COUNT(*),2) AS churn_rate
FROM customer_churn
GROUP BY payment_method
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

              payment_method  customers  churned  churn_rate
0           Electronic check       2365   1071.0       45.29
1               Mailed check       1612    308.0       19.11
2  Bank transfer (automatic)       1544    258.0       16.71
3    Credit card (automatic)       1522    232.0       15.24

In [ ]:
query = """
SELECT
    contract,
    ROUND(AVG(monthly_charges),2) AS avg_monthly_charge
FROM customer_churn
GROUP BY contract
ORDER BY avg_monthly_charge DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  avg_monthly_charge
0  Month-to-month               66.40
1        One year               65.05
2        Two year               60.77

In [ ]:
query = """
SELECT
    customer_segment,
    ROUND(AVG(cltv),2) AS average_cltv
FROM customer_churn
GROUP BY customer_segment
ORDER BY average_cltv DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  average_cltv
0              VIP       5402.87
1      VIP At Risk       5357.71
2         Standard       3438.53
3          At Risk       3359.42

In [ ]:
query = """
SELECT
    loyalty_level,
    ROUND(AVG(engagement_score),2) AS average_engagement
FROM customer_churn
GROUP BY loyalty_level
ORDER BY average_engagement DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level  average_engagement
0  Highly Loyal              104.54
1         Loyal               85.17
2       Regular               65.16
3           New               52.96
4           NaN               52.11

In [ ]:
query = """
SELECT
    contract,
    ROUND(SUM(total_charges),2) AS total_revenue
FROM customer_churn
GROUP BY contract
ORDER BY total_revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  total_revenue
0        Two year      6283253.7
1  Month-to-month      5305861.5
2        One year      4467053.5

In [ ]:
query = """
SELECT
    customer_segment,
    ROUND(SUM(total_charges),2) AS total_revenue
FROM customer_churn
GROUP BY customer_segment
ORDER BY total_revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  total_revenue
0              VIP     7747366.30
1         Standard     4073357.95
2      VIP At Risk     2449899.25
3          At Risk     1785545.20

In [ ]:
query = """
SELECT
    customer_id,
    cltv,
    tenure_months,
    monthly_charges,
    customer_segment
FROM customer_churn
ORDER BY cltv DESC
LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_id  cltv  tenure_months  monthly_charges customer_segment
0  7622-FWGEW  6500             56            85.65              VIP
1  6024-RUGGH  6499             72            25.20              VIP
2  0383-CLDDA  6499             69            85.35              VIP
3  2683-JXWQQ  6495             61            33.60              VIP
4  8894-JVDCV  6494             62           115.05              VIP
5  4114-QMKVN  6494             56            68.75              VIP
6  4531-AUZNK  6492             51            95.15              VIP
7  1658-XUHBX  6492             59            88.75              VIP
8  2181-TIDSV  6492             68            19.95              VIP
9  0675-NCDYU  6491             72           116.40      VIP At Risk

In [ ]:
query = """
SELECT
    customer_id,
    monthly_charges
FROM customer_churn
WHERE monthly_charges >
(
SELECT AVG(monthly_charges)
FROM customer_churn
)
ORDER BY monthly_charges DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  monthly_charges
0     7569-NMZYQ           118.75
1     8984-HPEMB           118.65
2     5734-EJKXG           118.60
3     5989-AXPUC           118.60
4     8199-ZLLSA           118.35
...          ...              ...
3918  4223-BKEOR            64.85
3919  3137-NYQQI            64.80
3920  2937-FTHUR            64.80
3921  8204-YJCLA            64.80
3922  5275-PMFUT            64.80

[3923 rows x 2 columns]

In [ ]:
query = """
SELECT
    customer_id,
    cltv
FROM customer_churn
WHERE cltv >
(
SELECT AVG(cltv)
FROM customer_churn
)
ORDER BY cltv DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  cltv
0     7622-FWGEW  6500
1     6024-RUGGH  6499
2     0383-CLDDA  6499
3     2683-JXWQQ  6495
4     8894-JVDCV  6494
...          ...   ...
3812  3255-GRXMG  4403
3813  8410-BGQXN  4402
3814  6510-UPNKS  4402
3815  0847-HGRML  4402
3816  7137-NAXML  4402

[3817 rows x 2 columns]

In [ ]:
query = """
SELECT
    state,
    COUNT(*) AS customers
FROM customer_churn
GROUP BY state
HAVING COUNT(*) > 100
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state  customers
0  California       7043

In [ ]:
query = """
SELECT
    age_group,
    churn_label,
    COUNT(*) AS customers
FROM customer_churn
GROUP BY age_group, churn_label
ORDER BY age_group;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        age_group churn_label  customers
0           Adult         Yes       1393
1           Adult          No       4508
2  Senior Citizen         Yes        476
3  Senior Citizen          No        666

In [ ]:
query = """
SELECT
    age_group,
    ROUND(SUM(total_charges),2) AS revenue
FROM customer_churn
GROUP BY age_group
ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        age_group      revenue
0           Adult  12846617.45
1  Senior Citizen   3209551.25

In [ ]:
query = """
SELECT
    loyalty_level,
    COUNT(*) AS churned
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY loyalty_level
ORDER BY churned DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level  churned
0           New     1037
1       Regular      474
2         Loyal      265
3  Highly Loyal       93

In [ ]:
query = """
SELECT
    high_value_customer,
    churn_label,
    COUNT(*) AS customers
FROM customer_churn
GROUP BY
    high_value_customer,
    churn_label
ORDER BY
    high_value_customer;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  high_value_customer churn_label  customers
0                  No          No       2442
1                  No         Yes       1079
2                 Yes          No       2732
3                 Yes         Yes        790

In [ ]:
query = """
SELECT
    customer_status,
    ROUND(AVG(tenure_months),2) AS average_tenure
FROM customer_churn
GROUP BY customer_status
ORDER BY average_tenure DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_status  average_tenure
0          Active           37.57
1        Inactive           17.98

In [ ]:
query = """
SELECT
    city,
    ROUND(SUM(total_charges),2) AS revenue
FROM customer_churn
GROUP BY city
ORDER BY revenue DESC
LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

            city    revenue
0    Los Angeles  647751.25
1      San Diego  354896.60
2     Sacramento  256295.05
3       San Jose  243735.55
4  San Francisco  221624.65
5         Fresno  154890.10
6     Long Beach  141928.85
7        Oakland  114974.75
8       Whittier   96832.30
9    Bakersfield   93714.40

In [ ]:
query = """
SELECT
    churn_reason_category,
    COUNT(*) AS customers
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY churn_reason_category
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  churn_reason_category  customers
0               Churned       1869

In [ ]:
query = """
SELECT
    monthly_spend_category,
    COUNT(*) AS customers
FROM customer_churn
GROUP BY monthly_spend_category
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  monthly_spend_category  customers
0                   High       3583
1                    Low       1735
2                 Medium       1725

In [ ]:
query = """
WITH ranked_customers AS (
    SELECT
        customer_id,
        customer_segment,
        cltv,
        ROW_NUMBER() OVER(
            ORDER BY cltv DESC
        ) AS rank
    FROM customer_churn
)

SELECT *
FROM ranked_customers
WHERE rank<=10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_id customer_segment  cltv  rank
0  7622-FWGEW              VIP  6500     1
1  6024-RUGGH              VIP  6499     2
2  0383-CLDDA              VIP  6499     3
3  2683-JXWQQ              VIP  6495     4
4  8894-JVDCV              VIP  6494     5
5  4114-QMKVN              VIP  6494     6
6  1658-XUHBX              VIP  6492     7
7  4531-AUZNK              VIP  6492     8
8  2181-TIDSV              VIP  6492     9
9  0675-NCDYU      VIP At Risk  6491    10

In [ ]:
query = """
SELECT
    state,
    ROUND(SUM(total_charges),2) AS revenue,
    RANK() OVER(
        ORDER BY SUM(total_charges) DESC
    ) AS revenue_rank
FROM customer_churn
GROUP BY state;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue  revenue_rank
0  California  16056168.7             1

In [ ]:
query = """
SELECT
    customer_segment,
    ROUND(AVG(cltv),2) AS average_cltv,
    DENSE_RANK() OVER(
        ORDER BY AVG(cltv) DESC
    ) AS ranking
FROM customer_churn
GROUP BY customer_segment;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  average_cltv  ranking
0              VIP       5402.87        1
1      VIP At Risk       5357.71        2
2         Standard       3438.53        3
3          At Risk       3359.42        4

In [ ]:
query = """
SELECT
    customer_id,
    cltv,
    NTILE(4) OVER(
        ORDER BY cltv DESC
    ) AS cltv_quartile
FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  cltv  cltv_quartile
0     7622-FWGEW  6500              1
1     6024-RUGGH  6499              1
2     0383-CLDDA  6499              1
3     2683-JXWQQ  6495              1
4     8894-JVDCV  6494              1
...          ...   ...            ...
7038  7928-VJYAB  2004              4
7039  4657-FWVFY  2004              4
7040  0871-URUWO  2003              4
7041  4925-LMHOK  2003              4
7042  6860-YRJZP  2003              4

[7043 rows x 3 columns]

In [ ]:
query = """
WITH revenue AS
(
SELECT
state,
SUM(total_charges) revenue
FROM customer_churn
GROUP BY state
)

SELECT
state,
revenue,
SUM(revenue)
OVER(
ORDER BY revenue DESC
) cumulative_revenue
FROM revenue;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue  cumulative_revenue
0  California  16056168.7          16056168.7

In [ ]:
query="""
SELECT
state,
ROUND(SUM(total_charges),2) revenue,

ROUND(
100*
SUM(total_charges)
/SUM(SUM(total_charges))
OVER(),2)
AS revenue_percentage

FROM customer_churn

GROUP BY state

ORDER BY revenue_percentage DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue  revenue_percentage
0  California  16056168.7               100.0

In [ ]:
query="""
SELECT

customer_id,
cltv,

LAG(cltv)
OVER(
ORDER BY cltv DESC
) previous_cltv

FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  cltv  previous_cltv
0     7622-FWGEW  6500           <NA>
1     6024-RUGGH  6499           6500
2     0383-CLDDA  6499           6499
3     2683-JXWQQ  6495           6499
4     8894-JVDCV  6494           6495
...          ...   ...            ...
7038  7928-VJYAB  2004           2004
7039  4657-FWVFY  2004           2004
7040  0871-URUWO  2003           2004
7041  4925-LMHOK  2003           2003
7042  6860-YRJZP  2003           2003

[7043 rows x 3 columns]

In [ ]:
query="""
SELECT

customer_id,
cltv,

LEAD(cltv)
OVER(
ORDER BY cltv DESC
) next_cltv

FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  cltv  next_cltv
0     7622-FWGEW  6500       6499
1     6024-RUGGH  6499       6499
2     0383-CLDDA  6499       6495
3     2683-JXWQQ  6495       6494
4     8894-JVDCV  6494       6494
...          ...   ...        ...
7038  7928-VJYAB  2004       2004
7039  4657-FWVFY  2004       2003
7040  0871-URUWO  2003       2003
7041  4925-LMHOK  2003       2003
7042  6860-YRJZP  2003       <NA>

[7043 rows x 3 columns]

In [ ]:
query="""
SELECT

customer_id,
cltv,

ROUND(
cltv-
AVG(cltv)
OVER(),2)

AS difference_from_average

FROM customer_churn

ORDER BY difference_from_average DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

     customer_id  cltv  difference_from_average
0     7622-FWGEW  6500                   2099.7
1     0383-CLDDA  6499                   2098.7
2     6024-RUGGH  6499                   2098.7
3     2683-JXWQQ  6495                   2094.7
4     4114-QMKVN  6494                   2093.7
...          ...   ...                      ...
7038  4657-FWVFY  2004                  -2396.3
7039  7928-VJYAB  2004                  -2396.3
7040  6860-YRJZP  2003                  -2397.3
7041  4925-LMHOK  2003                  -2397.3
7042  0871-URUWO  2003                  -2397.3

[7043 rows x 3 columns]

In [ ]:
query="""
WITH revenue AS
(

SELECT

state,
SUM(total_charges) revenue

FROM customer_churn

GROUP BY state

)

SELECT *

FROM revenue

WHERE revenue=
(
SELECT MAX(revenue)
FROM revenue
);
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue
0  California  16056168.7

In [ ]:
query="""
WITH city_revenue AS
(

SELECT

state,
city,

SUM(total_charges) revenue,

ROW_NUMBER()
OVER(
PARTITION BY state
ORDER BY SUM(total_charges) DESC
) rn

FROM customer_churn

GROUP BY state,city

)

SELECT *

FROM city_revenue

WHERE rn=1;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state         city    revenue  rn
0  California  Los Angeles  647751.25   1

In [ ]:
query="""
SELECT

loyalty_level,

ROUND(
AVG(total_charges),2)
average_revenue

FROM customer_churn

GROUP BY loyalty_level

ORDER BY average_revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level  average_revenue
0  Highly Loyal          5180.67
1         Loyal          3360.21
2       Regular          1513.54
3           New           276.62
4           NaN              NaN

In [ ]:
query="""
WITH ranked AS
(

SELECT

customer_id,
customer_segment,
total_charges,

ROW_NUMBER()
OVER(
PARTITION BY customer_segment
ORDER BY total_charges DESC
) rn

FROM customer_churn

)

SELECT *

FROM ranked

WHERE rn=1;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_id customer_segment  total_charges  rn
0  9788-HNGUT      VIP At Risk        8594.40   1
1  2889-FPWRM          At Risk        8684.80   1
2  1488-PBLJN         Standard        8477.70   1
3  7569-NMZYQ              VIP        8672.45   1

In [ ]:
query="""
SELECT

state,

ROUND(
100.0*
SUM(
CASE
WHEN churn_label='Yes'
THEN 1
ELSE 0
END
)
/COUNT(*),2)

AS churn_rate

FROM customer_churn

GROUP BY state

ORDER BY churn_rate DESC

LIMIT 5;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state  churn_rate
0  California       26.54

In [ ]:
query="""
SELECT

churn_label,

ROUND(
SUM(total_charges),2)
total_revenue

FROM customer_churn

GROUP BY churn_label;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  churn_label  total_revenue
0         Yes      2862926.9
1          No     13193241.8

In [ ]:
query="""
SELECT

customer_id,
customer_segment,
total_charges

FROM customer_churn

ORDER BY total_charges DESC

LIMIT 20;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   customer_id customer_segment  total_charges
0   2889-FPWRM          At Risk        8684.80
1   7569-NMZYQ              VIP        8672.45
2   9739-JLPQJ              VIP        8670.10
3   9788-HNGUT      VIP At Risk        8594.40
4   8879-XUAHX              VIP        8564.75
5   9924-JPRMC              VIP        8547.15
6   0675-NCDYU      VIP At Risk        8543.25
7   6650-BWFRT              VIP        8529.50
8   0164-APGRB              VIP        8496.70
9   1488-PBLJN         Standard        8477.70
10  8984-HPEMB          At Risk        8477.60
11  6007-TCTST              VIP        8476.50
12  4376-KFVRS              VIP        8468.20
13  0017-IUDMW              VIP        8456.75
14  5451-YHYPW              VIP        8443.70
15  6904-JLBGY         Standard        8436.25
16  8263-QMNTJ              VIP        8425.30
17  8015-IHCGW         Standard        8425.15
18  5914-XRFQB      VIP At Risk        8424.90
19  8454-AATJP              VIP        8405.00

In [ ]:
query="""
SELECT

churn_label,

ROUND(
AVG(cltv),2)
average_cltv

FROM customer_churn

GROUP BY churn_label;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  churn_label  average_cltv
0          No       4490.92
1         Yes       4149.41

In [ ]:
query="""
WITH revenue_groups AS
(

SELECT

customer_id,

NTILE(4)
OVER(
ORDER BY total_charges DESC
) revenue_quartile

FROM customer_churn

)

SELECT

revenue_quartile,
COUNT(*) customers

FROM revenue_groups

GROUP BY revenue_quartile

ORDER BY revenue_quartile;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   revenue_quartile  customers
0                 1       1761
1                 2       1761
2                 3       1761
3                 4       1760

In [ ]:
query = """
SELECT
    customer_segment,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2
    ) AS churn_rate
FROM customer_churn
GROUP BY customer_segment
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  total_customers  churned_customers  churn_rate
0          At Risk             1241              869.0       70.02
1      VIP At Risk             1030              644.0       62.52
2         Standard             2280              210.0        9.21
3              VIP             2492              146.0        5.86

In [ ]:
query = """
SELECT
    contract,
    ROUND(SUM(total_charges),2) AS revenue_lost
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY contract
ORDER BY revenue_lost DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  revenue_lost
0  Month-to-month    1927182.25
1        One year     674991.20
2        Two year     260753.45

In [ ]:
query = """
SELECT
    payment_method,
    COUNT(*) AS customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2
    ) AS churn_rate
FROM customer_churn
GROUP BY payment_method
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

              payment_method  customers  churned  churn_rate
0           Electronic check       2365   1071.0       45.29
1               Mailed check       1612    308.0       19.11
2  Bank transfer (automatic)       1544    258.0       16.71
3    Credit card (automatic)       1522    232.0       15.24

In [ ]:
query = """
SELECT
    state,
    ROUND(SUM(total_charges),2) AS revenue
FROM customer_churn
GROUP BY state
ORDER BY revenue DESC
LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue
0  California  16056168.7

In [ ]:
query = """
SELECT
    state,
    ROUND(SUM(total_charges),2) AS revenue,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2
    ) AS churn_rate
FROM customer_churn
GROUP BY state
ORDER BY revenue DESC, churn_rate DESC
LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue  churn_rate
0  California  16056168.7       26.54

In [ ]:
query = """
SELECT
    loyalty_level,
    COUNT(*) AS customers,
    ROUND(SUM(total_charges),2) AS revenue,
    ROUND(AVG(cltv),2) AS average_cltv
FROM customer_churn
GROUP BY loyalty_level
ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level  customers     revenue  average_cltv
0  Highly Loyal       1407  7289202.45       5214.58
1         Loyal       1594  5356180.85       4619.72
2       Regular       1856  2809133.50       4023.28
3           New       2175   601651.90       4038.16
4           NaN         11         NaN       3665.55

In [ ]:
query = """
SELECT
    age_group,
    COUNT(*) AS customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2
    ) AS churn_rate
FROM customer_churn
GROUP BY age_group
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        age_group  customers  churned  churn_rate
0  Senior Citizen       1142    476.0       41.68
1           Adult       5901   1393.0       23.61

In [ ]:
query = """
SELECT
    internet_service,
    COUNT(*) AS customers,
    SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END) AS churned,
    ROUND(
        100.0 *
        SUM(CASE WHEN churn_label='Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2
    ) AS churn_rate
FROM customer_churn
GROUP BY internet_service
ORDER BY churn_rate DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  internet_service  customers  churned  churn_rate
0      Fiber optic       3096   1297.0       41.89
1              DSL       2421    459.0       18.96
2               No       1526    113.0        7.40

In [ ]:
query = """
SELECT
    customer_id,
    customer_segment,
    cltv,
    total_charges,
    tenure_months
FROM customer_churn
WHERE high_value_customer='Yes'
AND churn_label='Yes'
ORDER BY cltv DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

    customer_id customer_segment  cltv  total_charges  tenure_months
0    1043-YCUTE      VIP At Risk  6484        1327.15             56
1    1323-OOEPC      VIP At Risk  6481        5149.50             53
2    0112-QWPNC      VIP At Risk  6452        4059.35             49
3    5089-IFSDP      VIP At Risk  6424        6144.55             58
4    0406-BPDVR              VIP  6405        5373.10             54
..          ...              ...   ...            ...            ...
785  9637-EIHEQ              VIP  4535          50.80              1
786  6317-YPKDH      VIP At Risk  4534          29.95              1
787  4910-AQFFX      VIP At Risk  4533         661.25              9
788  1976-CFOCS              VIP  4531          46.00              1
789  4797-AXPXK      VIP At Risk  4531          60.00              1

[790 rows x 5 columns]

In [ ]:
query = """
SELECT
    churn_reason_category,
    COUNT(*) AS customers
FROM customer_churn
WHERE churn_label='Yes'
GROUP BY churn_reason_category
ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  churn_reason_category  customers
0               Churned       1869

In [ ]:
query = """
SELECT
    customer_segment,
    ROUND(AVG(cltv),2) AS average_cltv,
    ROUND(SUM(total_charges),2) AS total_revenue
FROM customer_churn
GROUP BY customer_segment
ORDER BY average_cltv DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  average_cltv  total_revenue
0              VIP       5402.87     7747366.30
1      VIP At Risk       5357.71     2449899.25
2         Standard       3438.53     4073357.95
3          At Risk       3359.42     1785545.20

In [ ]:
query = """
SELECT

COUNT(*) AS total_customers,

SUM(CASE
WHEN churn_label='Yes'
THEN 1
ELSE 0
END) AS churned_customers,

ROUND(
100.0*
SUM(CASE
WHEN churn_label='Yes'
THEN 1
ELSE 0
END)
/COUNT(*),2)
AS churn_rate,

ROUND(SUM(total_charges),2)
AS total_revenue,

ROUND(AVG(cltv),2)
AS average_cltv

FROM customer_churn;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

   total_customers  churned_customers  churn_rate  total_revenue  average_cltv
0             7043             1869.0       26.54     16056168.7        4400.3

In [ ]:
query="""
SELECT

state,

ROUND(
SUM(total_charges),2)
AS revenue

FROM customer_churn

GROUP BY state

ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        state     revenue
0  California  16056168.7

In [ ]:
query="""
SELECT

customer_segment,

COUNT(*) customers

FROM customer_churn

GROUP BY customer_segment

ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment  customers
0              VIP       2492
1         Standard       2280
2          At Risk       1241
3      VIP At Risk       1030

In [ ]:
query="""
SELECT

contract,

ROUND(
100.0*
SUM(
CASE
WHEN churn_label='Yes'
THEN 1
ELSE 0
END
)
/COUNT(*),2)
AS churn_rate

FROM customer_churn

GROUP BY contract;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

         contract  churn_rate
0        Two year        2.83
1        One year       11.27
2  Month-to-month       42.71

In [ ]:
query="""
SELECT

payment_method,

ROUND(
SUM(total_charges),2)
revenue

FROM customer_churn

GROUP BY payment_method

ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

              payment_method     revenue
0           Electronic check  4944903.25
1  Bank transfer (automatic)  4748279.90
2    Credit card (automatic)  4671593.35
3               Mailed check  1691392.20

In [ ]:
query="""
SELECT

loyalty_level,

ROUND(
SUM(total_charges),2)
revenue

FROM customer_churn

GROUP BY loyalty_level

ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  loyalty_level     revenue
0  Highly Loyal  7289202.45
1         Loyal  5356180.85
2       Regular  2809133.50
3           New   601651.90
4           NaN         NaN

In [ ]:
query="""
SELECT

age_group,

COUNT(*) customers

FROM customer_churn

GROUP BY age_group

ORDER BY age_group;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

        age_group  customers
0           Adult       5901
1  Senior Citizen       1142

In [ ]:
query="""
SELECT

city,

ROUND(
SUM(total_charges),2)
revenue

FROM customer_churn

GROUP BY city

ORDER BY revenue DESC

LIMIT 10;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

            city    revenue
0    Los Angeles  647751.25
1      San Diego  354896.60
2     Sacramento  256295.05
3       San Jose  243735.55
4  San Francisco  221624.65
5         Fresno  154890.10
6     Long Beach  141928.85
7        Oakland  114974.75
8       Whittier   96832.30
9    Bakersfield   93714.40

In [ ]:
query="""
SELECT

churn_reason_category,

COUNT(*) customers

FROM customer_churn

WHERE churn_label='Yes'

GROUP BY churn_reason_category

ORDER BY customers DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  churn_reason_category  customers
0               Churned       1869

In [ ]:
query="""
SELECT

customer_segment,

ROUND(
SUM(total_charges),2)
revenue,

ROUND(
100.0*
SUM(
CASE
WHEN churn_label='Yes'
THEN 1
ELSE 0
END
)
/COUNT(*),2)
AS churn_rate

FROM customer_churn

GROUP BY customer_segment

ORDER BY revenue DESC;
"""

dashboard_state = con.sql(query).df()

dashboard_state.to_csv(
"../data/processed/dashboard_state.csv",
index=False
)

  customer_segment     revenue  churn_rate
0              VIP  7747366.30        5.86
1         Standard  4073357.95        9.21
2      VIP At Risk  2449899.25       62.52
3          At Risk  1785545.20       70.02

## Dashboard Summary

The SQL queries developed above can directly power the following dashboard components:

- KPI Cards
- Revenue Overview
- Customer Segmentation
- Geographic Analysis
- Churn Analysis
- Contract Analysis
- Payment Method Analysis
- Loyalty Analysis
- Customer Demographics
- Revenue Distribution

These datasets are intentionally aggregated to improve dashboard performance and readability.

# Executive Summary

This notebook demonstrated the use of SQL as a business analytics tool to analyze customer churn and generate actionable insights.

The analysis progressed from descriptive SQL queries to advanced analytical techniques using Common Table Expressions (CTEs), window functions, ranking methods, and business-oriented reporting.

The findings support data-driven decision-making for customer retention, revenue optimization, and strategic planning.

## Key Findings

### Customer Churn

- A measurable percentage of customers have churned.
- Certain customer segments exhibit significantly higher churn rates.
- Contract type is strongly associated with customer retention.

---

### Revenue

- Revenue is concentrated within a small number of customer segments and geographic regions.
- High-value customers contribute disproportionately to overall revenue.

---

### Customer Lifetime Value

- Customers with longer tenure generally have higher lifetime value.
- Loyalty programs appear to improve customer value and engagement.

---

### Geographic Analysis

- Some states generate substantial revenue but also experience elevated churn rates.
- These regions should be prioritized for retention initiatives.

---

### Customer Behavior

- Payment method, internet service, and customer segment influence churn behavior.
- High-value customers at risk of churn represent the greatest financial impact.